### ISSUE TITLE
In-band error indication

### ISSUE THREAD

**Issue by odelande** [ARM-software/speculation-barrier#2]
Your API uses a `__failval` argument as the value to return upon failure, which means that a caller cannot distinguish between a bound check failure, and a successful check followed by a load returning the same value as `__failval`. If the caller cannot sacrify a value to represent failures in this way, then they must make a second call with a different `__failval` value in case the first one fails.

The API could use another style, by taking a pointer to a buffer in which to write the loaded value, and returning a boolean.

**Comment by jgreenhalgh-arm** [comment]
Hi,

Thanks for your feedback. I'm sorry to immediately close this issue without a more detailed response to your technical points, but as this is feedback on the API provided by the proposed intrinsic, rather than an issue with the implementation of the intrinsic found in this project, or the documentation of this project, I think it is off-topic for the issue tracker on this repository.

If you would like to give feedback on the proposed intrinsic, or otherwise need to talk to Arm about this, please use the contact details given at www.arm.com/security-update .

Best Regards,
James Greenhalgh

**Comment by odelande** [comment]
Agreed. I reported my feedback as you suggested.
